/*
Device Type-7 APIs

APIs to get information about the HPE Alletra Storage MP X10000 system

API version: 0.1.0
Contact: object-svc-team@hpe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetGroupDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGroupDetails{}

// GetGroupDetails Response Body for device-type7 groups
type GetGroupDetails struct {
	Items []GroupItem `json:"items,omitempty"`
	PageLimit NullableInt64 `json:"pageLimit,omitempty"`
	PageOffset NullableInt64 `json:"pageOffset,omitempty"`
	Total NullableInt64 `json:"total,omitempty"`
}

// NewGetGroupDetails instantiates a new GetGroupDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGroupDetails() *GetGroupDetails {
	this := GetGroupDetails{}
	return &this
}

// NewGetGroupDetailsWithDefaults instantiates a new GetGroupDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGroupDetailsWithDefaults() *GetGroupDetails {
	this := GetGroupDetails{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetGroupDetails) GetItems() []GroupItem {
	if o == nil {
		var ret []GroupItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGroupDetails) GetItemsOk() ([]GroupItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GetGroupDetails) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []GroupItem and assigns it to the Items field.
func (o *GetGroupDetails) SetItems(v []GroupItem) {
	o.Items = v
}

// GetPageLimit returns the PageLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetGroupDetails) GetPageLimit() int64 {
	if o == nil || IsNil(o.PageLimit.Get()) {
		var ret int64
		return ret
	}
	return *o.PageLimit.Get()
}

// GetPageLimitOk returns a tuple with the PageLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGroupDetails) GetPageLimitOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.PageLimit.Get(), o.PageLimit.IsSet()
}

// HasPageLimit returns a boolean if a field has been set.
func (o *GetGroupDetails) HasPageLimit() bool {
	if o != nil && o.PageLimit.IsSet() {
		return true
	}

	return false
}

// SetPageLimit gets a reference to the given NullableInt64 and assigns it to the PageLimit field.
func (o *GetGroupDetails) SetPageLimit(v int64) {
	o.PageLimit.Set(&v)
}
// SetPageLimitNil sets the value for PageLimit to be an explicit nil
func (o *GetGroupDetails) SetPageLimitNil() {
	o.PageLimit.Set(nil)
}

// UnsetPageLimit ensures that no value is present for PageLimit, not even an explicit nil
func (o *GetGroupDetails) UnsetPageLimit() {
	o.PageLimit.Unset()
}

// GetPageOffset returns the PageOffset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetGroupDetails) GetPageOffset() int64 {
	if o == nil || IsNil(o.PageOffset.Get()) {
		var ret int64
		return ret
	}
	return *o.PageOffset.Get()
}

// GetPageOffsetOk returns a tuple with the PageOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGroupDetails) GetPageOffsetOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.PageOffset.Get(), o.PageOffset.IsSet()
}

// HasPageOffset returns a boolean if a field has been set.
func (o *GetGroupDetails) HasPageOffset() bool {
	if o != nil && o.PageOffset.IsSet() {
		return true
	}

	return false
}

// SetPageOffset gets a reference to the given NullableInt64 and assigns it to the PageOffset field.
func (o *GetGroupDetails) SetPageOffset(v int64) {
	o.PageOffset.Set(&v)
}
// SetPageOffsetNil sets the value for PageOffset to be an explicit nil
func (o *GetGroupDetails) SetPageOffsetNil() {
	o.PageOffset.Set(nil)
}

// UnsetPageOffset ensures that no value is present for PageOffset, not even an explicit nil
func (o *GetGroupDetails) UnsetPageOffset() {
	o.PageOffset.Unset()
}

// GetTotal returns the Total field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetGroupDetails) GetTotal() int64 {
	if o == nil || IsNil(o.Total.Get()) {
		var ret int64
		return ret
	}
	return *o.Total.Get()
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGroupDetails) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Total.Get(), o.Total.IsSet()
}

// HasTotal returns a boolean if a field has been set.
func (o *GetGroupDetails) HasTotal() bool {
	if o != nil && o.Total.IsSet() {
		return true
	}

	return false
}

// SetTotal gets a reference to the given NullableInt64 and assigns it to the Total field.
func (o *GetGroupDetails) SetTotal(v int64) {
	o.Total.Set(&v)
}
// SetTotalNil sets the value for Total to be an explicit nil
func (o *GetGroupDetails) SetTotalNil() {
	o.Total.Set(nil)
}

// UnsetTotal ensures that no value is present for Total, not even an explicit nil
func (o *GetGroupDetails) UnsetTotal() {
	o.Total.Unset()
}

func (o GetGroupDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGroupDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.PageLimit.IsSet() {
		toSerialize["pageLimit"] = o.PageLimit.Get()
	}
	if o.PageOffset.IsSet() {
		toSerialize["pageOffset"] = o.PageOffset.Get()
	}
	if o.Total.IsSet() {
		toSerialize["total"] = o.Total.Get()
	}
	return toSerialize, nil
}

type NullableGetGroupDetails struct {
	value *GetGroupDetails
	isSet bool
}

func (v NullableGetGroupDetails) Get() *GetGroupDetails {
	return v.value
}

func (v *NullableGetGroupDetails) Set(val *GetGroupDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGroupDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGroupDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGroupDetails(val *GetGroupDetails) *NullableGetGroupDetails {
	return &NullableGetGroupDetails{value: val, isSet: true}
}

func (v NullableGetGroupDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGroupDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


