/*
Device Type-7 APIs

APIs to get information about the HPE Alletra Storage MP X10000 system

API version: 0.1.0
Contact: object-svc-team@hpe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ObjectUpdateGroupBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectUpdateGroupBody{}

// ObjectUpdateGroupBody Group update request body
type ObjectUpdateGroupBody struct {
	// Users name list to add in the group
	Users []string `json:"users,omitempty"`
}

// NewObjectUpdateGroupBody instantiates a new ObjectUpdateGroupBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectUpdateGroupBody() *ObjectUpdateGroupBody {
	this := ObjectUpdateGroupBody{}
	return &this
}

// NewObjectUpdateGroupBodyWithDefaults instantiates a new ObjectUpdateGroupBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectUpdateGroupBodyWithDefaults() *ObjectUpdateGroupBody {
	this := ObjectUpdateGroupBody{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *ObjectUpdateGroupBody) GetUsers() []string {
	if o == nil || IsNil(o.Users) {
		var ret []string
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectUpdateGroupBody) GetUsersOk() ([]string, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *ObjectUpdateGroupBody) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []string and assigns it to the Users field.
func (o *ObjectUpdateGroupBody) SetUsers(v []string) {
	o.Users = v
}

func (o ObjectUpdateGroupBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectUpdateGroupBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	return toSerialize, nil
}

type NullableObjectUpdateGroupBody struct {
	value *ObjectUpdateGroupBody
	isSet bool
}

func (v NullableObjectUpdateGroupBody) Get() *ObjectUpdateGroupBody {
	return v.value
}

func (v *NullableObjectUpdateGroupBody) Set(val *ObjectUpdateGroupBody) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectUpdateGroupBody) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectUpdateGroupBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectUpdateGroupBody(val *ObjectUpdateGroupBody) *NullableObjectUpdateGroupBody {
	return &NullableObjectUpdateGroupBody{value: val, isSet: true}
}

func (v NullableObjectUpdateGroupBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectUpdateGroupBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


