/*
Device Type-7 APIs

APIs to get information about the HPE Alletra Storage MP X10000 system

API version: 0.1.0
Contact: object-svc-team@hpe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObjectCreateGroupBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectCreateGroupBody{}

// ObjectCreateGroupBody Group creation request body
type ObjectCreateGroupBody struct {
	// Name of the group to be created
	Name string `json:"name"`
	// Users name list to add in the group
	Users []string `json:"users,omitempty"`
}

type _ObjectCreateGroupBody ObjectCreateGroupBody

// NewObjectCreateGroupBody instantiates a new ObjectCreateGroupBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectCreateGroupBody(name string) *ObjectCreateGroupBody {
	this := ObjectCreateGroupBody{}
	this.Name = name
	return &this
}

// NewObjectCreateGroupBodyWithDefaults instantiates a new ObjectCreateGroupBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectCreateGroupBodyWithDefaults() *ObjectCreateGroupBody {
	this := ObjectCreateGroupBody{}
	return &this
}

// GetName returns the Name field value
func (o *ObjectCreateGroupBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ObjectCreateGroupBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ObjectCreateGroupBody) SetName(v string) {
	o.Name = v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *ObjectCreateGroupBody) GetUsers() []string {
	if o == nil || IsNil(o.Users) {
		var ret []string
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectCreateGroupBody) GetUsersOk() ([]string, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *ObjectCreateGroupBody) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []string and assigns it to the Users field.
func (o *ObjectCreateGroupBody) SetUsers(v []string) {
	o.Users = v
}

func (o ObjectCreateGroupBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectCreateGroupBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	return toSerialize, nil
}

func (o *ObjectCreateGroupBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectCreateGroupBody := _ObjectCreateGroupBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varObjectCreateGroupBody)

	if err != nil {
		return err
	}

	*o = ObjectCreateGroupBody(varObjectCreateGroupBody)

	return err
}

type NullableObjectCreateGroupBody struct {
	value *ObjectCreateGroupBody
	isSet bool
}

func (v NullableObjectCreateGroupBody) Get() *ObjectCreateGroupBody {
	return v.value
}

func (v *NullableObjectCreateGroupBody) Set(val *ObjectCreateGroupBody) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectCreateGroupBody) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectCreateGroupBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectCreateGroupBody(val *ObjectCreateGroupBody) *NullableObjectCreateGroupBody {
	return &NullableObjectCreateGroupBody{value: val, isSet: true}
}

func (v NullableObjectCreateGroupBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectCreateGroupBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


