/*
Device Type-7 APIs

APIs to get information about the HPE Alletra Storage MP X10000 system

API version: 0.1.0
Contact: object-svc-team@hpe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBucketBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBucketBody{}

// CreateBucketBody Bucket creation request body
type CreateBucketBody struct {
	// Field to enable or disable compression for the bucket
	Compression *string `json:"compression,omitempty"`
	// Name of the bucket to be created
	Name string `json:"name"`
	// Tags for the bucket
	Tags []BucketTagsInner `json:"tags,omitempty"`
}

type _CreateBucketBody CreateBucketBody

// NewCreateBucketBody instantiates a new CreateBucketBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBucketBody(name string) *CreateBucketBody {
	this := CreateBucketBody{}
	this.Name = name
	return &this
}

// NewCreateBucketBodyWithDefaults instantiates a new CreateBucketBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBucketBodyWithDefaults() *CreateBucketBody {
	this := CreateBucketBody{}
	return &this
}

// GetCompression returns the Compression field value if set, zero value otherwise.
func (o *CreateBucketBody) GetCompression() string {
	if o == nil || IsNil(o.Compression) {
		var ret string
		return ret
	}
	return *o.Compression
}

// GetCompressionOk returns a tuple with the Compression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBucketBody) GetCompressionOk() (*string, bool) {
	if o == nil || IsNil(o.Compression) {
		return nil, false
	}
	return o.Compression, true
}

// HasCompression returns a boolean if a field has been set.
func (o *CreateBucketBody) HasCompression() bool {
	if o != nil && !IsNil(o.Compression) {
		return true
	}

	return false
}

// SetCompression gets a reference to the given string and assigns it to the Compression field.
func (o *CreateBucketBody) SetCompression(v string) {
	o.Compression = &v
}

// GetName returns the Name field value
func (o *CreateBucketBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateBucketBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateBucketBody) SetName(v string) {
	o.Name = v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBucketBody) GetTags() []BucketTagsInner {
	if o == nil {
		var ret []BucketTagsInner
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBucketBody) GetTagsOk() ([]BucketTagsInner, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateBucketBody) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []BucketTagsInner and assigns it to the Tags field.
func (o *CreateBucketBody) SetTags(v []BucketTagsInner) {
	o.Tags = v
}

func (o CreateBucketBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBucketBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Compression) {
		toSerialize["compression"] = o.Compression
	}
	toSerialize["name"] = o.Name
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *CreateBucketBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBucketBody := _CreateBucketBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBucketBody)

	if err != nil {
		return err
	}

	*o = CreateBucketBody(varCreateBucketBody)

	return err
}

type NullableCreateBucketBody struct {
	value *CreateBucketBody
	isSet bool
}

func (v NullableCreateBucketBody) Get() *CreateBucketBody {
	return v.value
}

func (v *NullableCreateBucketBody) Set(val *CreateBucketBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBucketBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBucketBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBucketBody(val *CreateBucketBody) *NullableCreateBucketBody {
	return &NullableCreateBucketBody{value: val, isSet: true}
}

func (v NullableCreateBucketBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBucketBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


