/*
Device Type-7 APIs

APIs to get information about the HPE Alletra Storage MP X10000 system

API version: 0.1.0
Contact: object-svc-team@hpe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAccessPolicyBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccessPolicyBody{}

// CreateAccessPolicyBody Access Policy create request body
type CreateAccessPolicyBody struct {
	// Name of the Access Policy to be created
	Name string `json:"name"`
	Statement []PolicyStatementInput `json:"statement"`
	// access policy version
	Version string `json:"version"`
}

type _CreateAccessPolicyBody CreateAccessPolicyBody

// NewCreateAccessPolicyBody instantiates a new CreateAccessPolicyBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccessPolicyBody(name string, statement []PolicyStatementInput, version string) *CreateAccessPolicyBody {
	this := CreateAccessPolicyBody{}
	this.Name = name
	this.Statement = statement
	this.Version = version
	return &this
}

// NewCreateAccessPolicyBodyWithDefaults instantiates a new CreateAccessPolicyBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccessPolicyBodyWithDefaults() *CreateAccessPolicyBody {
	this := CreateAccessPolicyBody{}
	return &this
}

// GetName returns the Name field value
func (o *CreateAccessPolicyBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAccessPolicyBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAccessPolicyBody) SetName(v string) {
	o.Name = v
}

// GetStatement returns the Statement field value
func (o *CreateAccessPolicyBody) GetStatement() []PolicyStatementInput {
	if o == nil {
		var ret []PolicyStatementInput
		return ret
	}

	return o.Statement
}

// GetStatementOk returns a tuple with the Statement field value
// and a boolean to check if the value has been set.
func (o *CreateAccessPolicyBody) GetStatementOk() ([]PolicyStatementInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Statement, true
}

// SetStatement sets field value
func (o *CreateAccessPolicyBody) SetStatement(v []PolicyStatementInput) {
	o.Statement = v
}

// GetVersion returns the Version field value
func (o *CreateAccessPolicyBody) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CreateAccessPolicyBody) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CreateAccessPolicyBody) SetVersion(v string) {
	o.Version = v
}

func (o CreateAccessPolicyBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccessPolicyBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["statement"] = o.Statement
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *CreateAccessPolicyBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"statement",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAccessPolicyBody := _CreateAccessPolicyBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAccessPolicyBody)

	if err != nil {
		return err
	}

	*o = CreateAccessPolicyBody(varCreateAccessPolicyBody)

	return err
}

type NullableCreateAccessPolicyBody struct {
	value *CreateAccessPolicyBody
	isSet bool
}

func (v NullableCreateAccessPolicyBody) Get() *CreateAccessPolicyBody {
	return v.value
}

func (v *NullableCreateAccessPolicyBody) Set(val *CreateAccessPolicyBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccessPolicyBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccessPolicyBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccessPolicyBody(val *CreateAccessPolicyBody) *NullableCreateAccessPolicyBody {
	return &NullableCreateAccessPolicyBody{value: val, isSet: true}
}

func (v NullableCreateAccessPolicyBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccessPolicyBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


