/*
Device Type-7 APIs

APIs to get information about the HPE Alletra Storage MP X10000 system

API version: 0.1.0
Contact: object-svc-team@hpe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// PolicyStatementInputResource - struct for PolicyStatementInputResource
type PolicyStatementInputResource struct {
	ArrayOfString *[]string
	String *string
}

// []stringAsPolicyStatementInputResource is a convenience function that returns []string wrapped in PolicyStatementInputResource
func ArrayOfStringAsPolicyStatementInputResource(v *[]string) PolicyStatementInputResource {
	return PolicyStatementInputResource{
		ArrayOfString: v,
	}
}

// stringAsPolicyStatementInputResource is a convenience function that returns string wrapped in PolicyStatementInputResource
func StringAsPolicyStatementInputResource(v *string) PolicyStatementInputResource {
	return PolicyStatementInputResource{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PolicyStatementInputResource) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			if err = validator.Validate(dst.ArrayOfString); err != nil {
				dst.ArrayOfString = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfString = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PolicyStatementInputResource)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PolicyStatementInputResource)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PolicyStatementInputResource) MarshalJSON() ([]byte, error) {
	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PolicyStatementInputResource) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePolicyStatementInputResource struct {
	value *PolicyStatementInputResource
	isSet bool
}

func (v NullablePolicyStatementInputResource) Get() *PolicyStatementInputResource {
	return v.value
}

func (v *NullablePolicyStatementInputResource) Set(val *PolicyStatementInputResource) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyStatementInputResource) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyStatementInputResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyStatementInputResource(val *PolicyStatementInputResource) *NullablePolicyStatementInputResource {
	return &NullablePolicyStatementInputResource{value: val, isSet: true}
}

func (v NullablePolicyStatementInputResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyStatementInputResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


