/*
Tasks REST APIs

APIs to get information about the tasks

API version: 0.1.0
Contact: sc-eng-tasks-ms@hpe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupIDNamePair type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupIDNamePair{}

// GroupIDNamePair struct for GroupIDNamePair
type GroupIDNamePair struct {
	// ID of the associated group
	Id string `json:"id"`
	// Name of the associated group
	Name string `json:"name"`
}

type _GroupIDNamePair GroupIDNamePair

// NewGroupIDNamePair instantiates a new GroupIDNamePair object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupIDNamePair(id string, name string) *GroupIDNamePair {
	this := GroupIDNamePair{}
	this.Id = id
	this.Name = name
	return &this
}

// NewGroupIDNamePairWithDefaults instantiates a new GroupIDNamePair object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupIDNamePairWithDefaults() *GroupIDNamePair {
	this := GroupIDNamePair{}
	return &this
}

// GetId returns the Id field value
func (o *GroupIDNamePair) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GroupIDNamePair) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GroupIDNamePair) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GroupIDNamePair) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GroupIDNamePair) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GroupIDNamePair) SetName(v string) {
	o.Name = v
}

func (o GroupIDNamePair) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupIDNamePair) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *GroupIDNamePair) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupIDNamePair := _GroupIDNamePair{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupIDNamePair)

	if err != nil {
		return err
	}

	*o = GroupIDNamePair(varGroupIDNamePair)

	return err
}

type NullableGroupIDNamePair struct {
	value *GroupIDNamePair
	isSet bool
}

func (v NullableGroupIDNamePair) Get() *GroupIDNamePair {
	return v.value
}

func (v *NullableGroupIDNamePair) Set(val *GroupIDNamePair) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupIDNamePair) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupIDNamePair) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupIDNamePair(val *GroupIDNamePair) *NullableGroupIDNamePair {
	return &NullableGroupIDNamePair{value: val, isSet: true}
}

func (v NullableGroupIDNamePair) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupIDNamePair) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


