/*
Tasks REST APIs

APIs to get information about the tasks

API version: 0.1.0
Contact: sc-eng-tasks-ms@hpe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TasksNotFound type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TasksNotFound{}

// TasksNotFound struct for TasksNotFound
type TasksNotFound struct {
	// Possible values: NOT_FOUND
	ErrorCode interface{} `json:"errorCode,omitempty"`
	// A user friendly error message
	Error string `json:"error"`
	// A unique identifier for the request
	TraceId string `json:"traceId"`
}

type _TasksNotFound TasksNotFound

// NewTasksNotFound instantiates a new TasksNotFound object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTasksNotFound(error_ string, errorCode string, traceId string) *TasksNotFound {
	this := TasksNotFound{}
	this.Error = error_
	this.ErrorCode = errorCode
	this.TraceId = traceId
	return &this
}

// NewTasksNotFoundWithDefaults instantiates a new TasksNotFound object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTasksNotFoundWithDefaults() *TasksNotFound {
	this := TasksNotFound{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TasksNotFound) GetErrorCode() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TasksNotFound) GetErrorCodeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return &o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *TasksNotFound) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given interface{} and assigns it to the ErrorCode field.
func (o *TasksNotFound) SetErrorCode(v interface{}) {
	o.ErrorCode = v
}

// GetError returns the Error field value
func (o *TasksNotFound) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *TasksNotFound) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *TasksNotFound) SetError(v string) {
	o.Error = v
}

// GetTraceId returns the TraceId field value
func (o *TasksNotFound) GetTraceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraceId
}

// GetTraceIdOk returns a tuple with the TraceId field value
// and a boolean to check if the value has been set.
func (o *TasksNotFound) GetTraceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraceId, true
}

// SetTraceId sets field value
func (o *TasksNotFound) SetTraceId(v string) {
	o.TraceId = v
}

func (o TasksNotFound) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TasksNotFound) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ErrorCode != nil {
		toSerialize["errorCode"] = o.ErrorCode
	}
	toSerialize["error"] = o.Error
	toSerialize["traceId"] = o.TraceId
	return toSerialize, nil
}

func (o *TasksNotFound) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"errorCode",
		"traceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTasksNotFound := _TasksNotFound{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTasksNotFound)

	if err != nil {
		return err
	}

	*o = TasksNotFound(varTasksNotFound)

	return err
}

type NullableTasksNotFound struct {
	value *TasksNotFound
	isSet bool
}

func (v NullableTasksNotFound) Get() *TasksNotFound {
	return v.value
}

func (v *NullableTasksNotFound) Set(val *TasksNotFound) {
	v.value = val
	v.isSet = true
}

func (v NullableTasksNotFound) IsSet() bool {
	return v.isSet
}

func (v *NullableTasksNotFound) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTasksNotFound(val *TasksNotFound) *NullableTasksNotFound {
	return &NullableTasksNotFound{value: val, isSet: true}
}

func (v NullableTasksNotFound) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTasksNotFound) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


