/*
Tasks REST APIs

APIs to get information about the tasks

API version: 0.1.0
Contact: sc-eng-tasks-ms@hpe.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TaskRecommendations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskRecommendations{}

// TaskRecommendations struct for TaskRecommendations
type TaskRecommendations struct {
	Message string `json:"message"`
}

type _TaskRecommendations TaskRecommendations

// NewTaskRecommendations instantiates a new TaskRecommendations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskRecommendations(message string) *TaskRecommendations {
	this := TaskRecommendations{}
	this.Message = message
	return &this
}

// NewTaskRecommendationsWithDefaults instantiates a new TaskRecommendations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskRecommendationsWithDefaults() *TaskRecommendations {
	this := TaskRecommendations{}
	return &this
}

// GetMessage returns the Message field value
func (o *TaskRecommendations) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TaskRecommendations) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TaskRecommendations) SetMessage(v string) {
	o.Message = v
}

func (o TaskRecommendations) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskRecommendations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *TaskRecommendations) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaskRecommendations := _TaskRecommendations{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaskRecommendations)

	if err != nil {
		return err
	}

	*o = TaskRecommendations(varTaskRecommendations)

	return err
}

type NullableTaskRecommendations struct {
	value *TaskRecommendations
	isSet bool
}

func (v NullableTaskRecommendations) Get() *TaskRecommendations {
	return v.value
}

func (v *NullableTaskRecommendations) Set(val *TaskRecommendations) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskRecommendations) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskRecommendations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskRecommendations(val *TaskRecommendations) *NullableTaskRecommendations {
	return &NullableTaskRecommendations{value: val, isSet: true}
}

func (v NullableTaskRecommendations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskRecommendations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


