/*
Device Type-7 APIs

Testing ObjectServicePortalAPIUIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	openapiclient "alletraMPX10000_sdk"
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_ObjectServicePortalAPIUIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ObjectServicePortalAPIUIAPIService BucketCapacityHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var systemId string
		var bucketId string

		resp, httpRes, err := apiClient.ObjectServicePortalAPIUIAPI.BucketCapacityHistory(context.Background(), systemId, bucketId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
